version: '3.8'

services:
  mysql:
    image: mysql:8.0
#    networks:
#      - db-net
    container_name: dorm-clean-management
    restart: always # 컨테이너가 종료되어도 항상 다시 시작
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: dorm_clean_management_db
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  nginx:
    image: nginx:latest
#    networks:
#      - web-net
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/templates/default.conf.template
    environment:
      - ADMIN_IP_LIST=${ADMIN_IP_LIST}
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  k6:
    image: grafana/k6:latest
#    networks:
#      - web-net
    container_name: k6-tester
    volumes:
      - ./k6:/scripts
    profiles:
      - testing # 평소(up -d)에는 실행 안 되게 프로필 설정

#networks:
#  web-net:
#    driver: bridge
#  db-net:
#    driver: bridge