name: Render Keep Alive (9AM-12AM KST)

on:
  schedule:
    - cron: '*/5 21-23,0-14 * * *'
    - cron: '0 15 * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send Health Check
        run: curl -s https://koreatech-dorm-management.onrender.com/health